sudo: false
addons:
  apt:
    packages:
      - libgd2-xpm-dev
      - graphviz
      - libxml2-dev
language: perl
perl:
  - "blead"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
env:
  global:
    - COVERAGE=1
    - DBICTEST_PG_DSN=dbi:Pg:dbname=sqlt_test
    - DBICTEST_PG_USER=postgres
matrix:
  allow_failures:
    - perl: "blead"
before_install:
  - eval $(curl https://travis-perl.github.io/init) --auto
install:
  - cpan-install --deps CGI DBD::SQLite XML::Parser DBD::Pg # Optional test deps
  - cpan-install Test::EOL Test::NoTabs # Author test deps
  - cpan-install --coverage
before_script:
  - psql -U postgres -c 'create database sqlt_test;'
